<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sbf_ajaxsolr"
 *
 * Auto generated by Extension Builder 2016-01-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'AjaxSolr',
	'description' => 'Solr client based on https://github.com/evolvingweb/ajax-solr.',
	'category' => 'plugin',
	'author' => 'Sebastian Gierth, Wolfram Eberius',
	'author_email' => 'sebastian.gierth@xima.de, edrush@posteo.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5.0-',
			'extbase' => '1.3-',
			'fluid' => '1.3-',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);